[2025-02-22T20:27:11.107+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_comic_fetcher.wait_for_comic scheduled__2025-02-19T05:00:00+00:00 [queued]>
[2025-02-22T20:27:11.110+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_comic_fetcher.wait_for_comic scheduled__2025-02-19T05:00:00+00:00 [queued]>
[2025-02-22T20:27:11.111+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-02-22T20:27:11.115+0000] {taskinstance.py:1380} INFO - Executing <Task(XKCDComicSensor): wait_for_comic> on 2025-02-19 05:00:00+00:00
[2025-02-22T20:27:11.117+0000] {standard_task_runner.py:57} INFO - Started process 189 to run task
[2025-02-22T20:27:11.119+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xkcd_comic_fetcher', 'wait_for_comic', 'scheduled__2025-02-19T05:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/xkcd-comics-dag.py', '--cfg-path', '/tmp/tmpazlyw4av']
[2025-02-22T20:27:11.120+0000] {standard_task_runner.py:85} INFO - Job 59: Subtask wait_for_comic
[2025-02-22T20:27:11.138+0000] {task_command.py:415} INFO - Running <TaskInstance: xkcd_comic_fetcher.wait_for_comic scheduled__2025-02-19T05:00:00+00:00 [running]> on host 25ffd23c4844
[2025-02-22T20:27:11.165+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_comic_fetcher' AIRFLOW_CTX_TASK_ID='wait_for_comic' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T05:00:00+00:00'
[2025-02-22T20:27:11.166+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-02-22T20:27:11.166+0000] {base.py:73} INFO - Using connection ID 'xkcd_db' for task execution.
[2025-02-22T20:27:11.168+0000] {sql.py:418} INFO - Running statement: SELECT MAX(comic_id) FROM public.comics, parameters: None
[2025-02-22T20:27:11.175+0000] {sql.py:427} INFO - Rows affected: 1
[2025-02-22T20:27:11.393+0000] {xkcd_sensor.py:60} INFO - No new comic available yet
[2025-02-22T20:30:47.859+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-02-22T20:30:47.862+0000] {process_utils.py:131} INFO - Sending 15 to group 189. PIDs of all processes in the group: [189]
[2025-02-22T20:30:47.862+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 189
[2025-02-22T20:30:47.862+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-22T20:30:47.869+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/sensors/base.py", line 285, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-02-22T20:30:47.872+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=xkcd_comic_fetcher, task_id=wait_for_comic, execution_date=20250219T050000, start_date=20250222T202711, end_date=20250222T203047
[2025-02-22T20:30:47.881+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 59 for task wait_for_comic (Task received SIGTERM signal; 189)
[2025-02-22T20:30:47.895+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=189, status='terminated', exitcode=1, started='20:27:11') (189) terminated with exit code 1
